#!/bin/sh

call_iptables() {
    /sbin/iptables "$@"
    /sbin/ip6tables "$@"
}

call_iptables --flush
call_iptables -A INPUT -p tcp --syn --dport 80 -j ACCEPT
call_iptables -A INPUT -p tcp --syn --dport 443 -j ACCEPT
call_iptables -A INPUT -p tcp --syn -i venet0 -j DROP
call_iptables -A INPUT -p tcp --syn -i venet0:0 -j DROP

call_iptables -A INPUT -p tcp ! --syn -m state --state NEW -j DROP
/sbin/iptables -A INPUT -f -j DROP
call_iptables -A INPUT -p tcp --tcp-flags ALL ALL -j DROP
call_iptables -A INPUT -p tcp --tcp-flags ALL NONE -j DROP
