#!/bin/sh

if [ "x$1" = 'x--daemon' ]; then
  nohup "$0" 0<&- &>/dev/null &
  exit 0
fi

PIPE=/run/sesame.pipe
GROUP=www-data
LOG=/var/log/sesame.log
SSH_PORT=`awk '/^Port/ {print $2}' /etc/ssh/sshd_config`

export LANG=C

log() {
  echo "[`date`] $1" >> $LOG
}

call_iptables() {
    /sbin/iptables "$@" 2>&1 > /dev/null
    /sbin/ip6tables "$@" 2>&1 > /dev/null
}

rm -f $PIPE
mkfifo $PIPE
chown root:$GROUP $PIPE
chmod 660 $PIPE

while true; do
  case `cat "$PIPE"` in
  open )
    if ! /sbin/iptables -n -L INPUT | grep -q " dpt:$SSH_PORT "; then
      log 'opening the door'
      call_iptables -I INPUT 1 -p tcp --syn --dport $SSH_PORT -j ACCEPT
    fi
    ;;
  close )
    if /sbin/iptables -n -L INPUT | grep -q " dpt:$SSH_PORT "; then
      log 'closing the door'
      call_iptables -D INPUT -p tcp --syn --dport $SSH_PORT -j ACCEPT
    fi
    ;;
  * )
    ;;
  esac
done
