#!/usr/bin/env python3

from functools import reduce
import os
import random
import sys

random.seed = os.urandom(1024)

ua = reduce(lambda x, y: x + chr(y), range(ord('A'), ord('Z') + 1), "")
la = ua.lower()
n = reduce(lambda x, y: x + chr(y), range(ord('0'), ord('9') + 1), "")

try:
  plength = int(sys.argv[1])
except:
  plength = 10

print(reduce(lambda x, y: x + random.choice(ua + la + n), range(plength), ""))
